name: integration_test
on: [push]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.x'
      - run: flutter pub get
      # - run: flutter build apk
      # - name: Unit test
      #   working-directory: ./android
      #   run: bash ./gradlew test --stacktrace

  # apk:
  #   name: Generate APK
  #   runs-on: ubuntu-18.04

  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Set up JDK 1.8
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         flutter-version: '2.0.x'
  #     - run: flutter pub get
  #     - run: flutter build apk

  #     - name: Assemble app debug APK
  #       working-directory: ./android
  #       run: bash ./gradlew assembleDebug --stacktrace
  #     - name: Upload app APK
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: app-debug
  #         path: build/app/outputs/apk/debug/app-debug.apk

  #     - name: Assemble Android Instrumentation Tests
  #       working-directory: ./android
  #       run: bash ./gradlew app:assembleAndroidTest
  #     - name: Upload Android Test APK
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: app-debug-androidTest
  #         path: build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk


  firebase:
    name: Run UI tests with Firebase Test Lab
    # needs: apk
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up auth
        # run: echo ${{ secrets.GCLOUD_AUTH }} > firebase_auth.json
        run: echo ${{ secrets.GCLOUD_AUTH }} | base64 -d > firebase_auth.json

      # - name: Download app APK
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: app-debug

      # - name: Download Android test APK
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: app-debug-androidTest


      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info
      - name: Activate
        run: gcloud auth activate-service-account --key-file=firebase_auth.json
      - name: list
        run: gcloud auth list
      - name: Run Instrumentation Tests in Firebase Test Lab
        run: GOOGLE_APPLICATION_CREDENTIALS="firebase_auth.json" gcloud firebase test android run --type instrumentation --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk --device model=Pixel2,version=30,locale=en,orientation=portrait